title: From Now On
email: qbration21@gmail.com
description: Technology, Life, and everything in between.
author: generation21
baseurl: "/fromnowon-blog"
url: "https://generation21.github.io"

# Social Profiles
twitter_username:
github_username: generation21
facebook_username:
instagram_username:
linkedin_username: generation21

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
